# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models

import adraft.notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=150, upload_to=adraft.notes.models.Attachment.upload_to, validators=[
                adraft.notes.models.FileValidator(content_types=('application/pdf', 'application/postscript', 'application/x-tex', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.graphics', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/x-dvi', 'application/x-latex', 'application/zip', 'application/gzip', 'text/csv', 'text/html', 'text/plain', 'image/gif', 'image/jpeg', 'image/pjpeg', 'image/png', 'image/svg+xml', 'image/tiff', 'image/vnd.microsoft.icon', 'image/vnd.wap.bmp'), max_size=10485760, min_size=10)]),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
