# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='html',
            field=models.TextField(blank=True, default='', verbose_name='HTML'),
        ),
    ]
